fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    versioning:
        enabled: true
    routing_loader:
        default_format: json
        include_format: true
    serializer:
        serialize_null: true
    format_listener:
            rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    view:
        view_response_listener: true
    access_denied_listener:
        json: true
