dsbaars_manage:
    resource: "@DsbaarsManageBundle/Controller/"
    type:     annotation
    prefix:   /manage

dsbaars_manage_api:
    resource: "@DsbaarsManageBundle/ApiController/"
    type:     annotation
    prefix:   /api/manage


dsbaars_betterpress:
    resource: "@DsbaarsBetterpressBundle/Controller/"
    type:     annotation
    prefix:   /

dsbaars_twenty_sixteen:
    resource: "@DsbaarsTwentySixteenBundle/Controller/"
    type:     annotation
    prefix:   /


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

home:
    path: /
    defaults:
        _controller: DsbaarsTwentySixteenBundle:Default:index
        path: /

root_sub:
    path: /manage/{rest}/{rest2}
    defaults:
        _controller: DsbaarsManageBundle:Default:index
        path: /manage


# Redirect everything else to index, so ui-router can take over
root:
    path: /manage/{rest}
    defaults:
        _controller: DsbaarsManageBundle:Default:index
        path: /manage

