services:
#    dsbaars_betterpress.example:
#        class: Dsbaars\Bundle\BetterpressBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.twig_extension:
        class: Dsbaars\Bundle\BetterpressBundle\Twig\Extension\BetterpressExtensions
        public: false
        tags:
            - { name: twig.extension }